Update Traditional Chinese Strings
ShareX/ShareX pull request #6034
Opened 2022-01-15 12:32 UTC by tony8077616

Update Traditional Chinese Strings

2022-01-15 18:01 UTC, toto6038 requested changes

2022-01-15 18:01 UTC, toto6038 commented on ShareX/Properties/Resources.zh-TW.resx
> +    <value>程序識別器</value>
同列546之留言

2022-01-15 22:51 UTC, Jaex commented
Why there is so many deleted/replaced lines in this PR? There should be only added lines, see example: #6006

2022-01-16 15:49 UTC, brlin-tw commented
I agree with @Jaex, maybe the line endings have been changed for the entire file?

@tony8077616 Can you fix it?

2022-01-16 16:34 UTC, tony8077616 commented
> Why there is so many deleted/replaced lines in this PR? There should be only added lines, see example: #6006

Hello sir 
I don't know why there are so many deleted/replaced with this file

I just...
1. Download the latest standalone version with that translate Application
2. Copy the ShareX from github and input that DIR to translate Application
3. Output Excel file from Translate Application
4. Add with translate and input excel file to translate Application
5. Get the update file in Properties and upload to github

So I don't know which step is the wrong...

2022-01-16 16:37 UTC, tony8077616 commented on ShareX/Properties/Resources.zh-TW.resx
> +    <value>程序名稱</value>
我是取自工作管理員的“處理程序”的部分，“處理序“還會給別人有缺字的狀況

2022-01-16 16:38 UTC, tony8077616 commented on ShareX/Properties/Resources.zh-TW.resx
> +    <value>程序名稱</value>
不然…
就乾脆直接叫做處理程序名稱好了

2022-01-16 16:40 UTC, tony8077616 commented
> > Why there is so many deleted/replaced lines in this PR? There should be only added lines, see example: #6006
> 
> Hello sir 
> I don't know why there are so many deleted/replaced with this file
> 
> I just...
> 1. Download the latest standalone version with that translate Application
> 2. Copy the ShareX from github and input that DIR to translate Application
> 3. Output Excel file from Translate Application
> 4. Add with translate and input excel file to translate Application
> 5. Get the update file in Properties and upload to github
> 
> So I don't know which step is the wrong...

I'll try to check out again in my free time ,may be tomorrow night if I don't forget

2022-01-17 15:59 UTC, tony8077616 commented
@Jaex I've already done for output
@brlin-tw Done for fixed the strings

2022-03-26 02:00 UTC, closed without merging